In [1]:
import torch
print(torch.__version__)

2.8.0+cpu


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)
print(a)
#empty() creates a tensor without initializing its values, so it may contain arbitrary data.

tensor([[-3.0757e-05,  8.9543e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.6576, 0.6135, 0.1991],
        [0.6550, 0.5641, 0.3221]])

In [11]:
# use of seed
torch.rand(2,3)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [15]:
# manual_seed -> same random numbers
print(torch.manual_seed(100))
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye -> identity matrix
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
#empty_like() is for creating a tensor with the same shape as a given tensor but without initializing its values.
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [24]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [25]:
# find data type
x.dtype

torch.int64

In [29]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [30]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [31]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [32]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [36]:
# addition
print(x + 2)
# substraction
x - 2
# multiplication
print(x * 3)
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### 2. Element wise operation

In [37]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [39]:
# add
print(a + b)
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])


tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [40]:
c = torch.tensor([1, -2, 3, -4])

In [41]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [43]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [44]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [45]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [46]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [47]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [53]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [54]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [55]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [56]:
# median
torch.median(e)

tensor(4.)

In [57]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [58]:
# product
torch.prod(e)

tensor(0.)

In [59]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [60]:
# variance
torch.var(e)

tensor(9.8667)

In [61]:
# argmax
torch.argmax(e)

tensor(3)

In [62]:
# argmin
torch.argmin(e)

tensor(5)

### 4. Matrix operations

In [63]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [64]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [65]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [66]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [67]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [68]:
# determinant
torch.det(h)

tensor(-315.)

In [69]:
# inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

### 5. Comparison operations

In [70]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [71]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [72]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [73]:
# log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [74]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [75]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [76]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [77]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [78]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

## Inplace Operations

In [79]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [80]:
m.add_(n)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [81]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [82]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [83]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [84]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [85]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

## Copying a Tensor

In [86]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [87]:
b = a

In [88]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [89]:
a[0][0] = 0

In [90]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [91]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [92]:
id(a)

2597235757264

In [93]:
id(b)

2597235757264

In [94]:
b = a.clone()

In [95]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [96]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [97]:
a[0][0] = 10

In [98]:
a

tensor([[10.0000,  0.8935,  0.0497],
        [ 0.1780,  0.3011,  0.1893]])

In [99]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [100]:
id(a)

2597235757264

In [101]:
id(b)

2597203365712